-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL CHECK (action = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text, 'status_change'::text, 'payment'::text, 'ai_action'::text])),
  entity text NOT NULL,
  entity_id uuid,
  changed_field text,
  old_value text,
  new_value text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner_name text,
  email text,
  phone text,
  address text,
  city text,
  province text,
  postal_code text,
  hst_number text,
  hourly_rate numeric DEFAULT 0,
  hst_rate numeric DEFAULT 0.13,
  tax_enabled boolean DEFAULT false,
  logo_url text,
  ai_profile jsonb DEFAULT '{
    "style": "professional",
    "verbosity": "balanced",
    "reminders": ["pets", "keys", "vip"],
    "learning_notes": ""
  }'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT businesses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text,
  email text,
  phone text,
  phone2 text,
  street text,
  city text,
  province text,
  postal_code text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'lead'::text, 'archived'::text])),
  referral_source text,
  notes text,
  access_info text,
  tags ARRAY DEFAULT '{}'::text[],
  ai_context jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.communication_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  client_id uuid NOT NULL,
  job_id uuid,
  logged_by uuid,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['Call'::text, 'Text'::text, 'Email'::text, 'In Person'::text, 'App'::text, 'Other'::text])),
  direction text NOT NULL CHECK (direction = ANY (ARRAY['Outbound'::text, 'Inbound'::text])),
  summary text,
  follow_up_required boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT communication_log_pkey PRIMARY KEY (id),
  CONSTRAINT communication_log_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT communication_log_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT communication_log_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT communication_log_logged_by_fkey FOREIGN KEY (logged_by) REFERENCES public.users(id)
);
CREATE TABLE public.config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  category text NOT NULL,
  key text NOT NULL,
  value text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT config_pkey PRIMARY KEY (id),
  CONSTRAINT config_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.expense_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  recorded_by uuid,
  expense_date date DEFAULT CURRENT_DATE,
  category text CHECK (category = ANY (ARRAY['Supplies'::text, 'Equipment'::text, 'Travel'::text, 'Marketing'::text, 'Other'::text])),
  amount numeric NOT NULL,
  notes text,
  receipt_url text,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT expense_log_pkey PRIMARY KEY (id),
  CONSTRAINT expense_log_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT expense_log_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  job_id uuid NOT NULL,
  CONSTRAINT invoice_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT invoice_jobs_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_jobs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  client_id uuid NOT NULL,
  invoice_number text,
  invoice_date date DEFAULT CURRENT_DATE,
  due_date date,
  total_amount numeric DEFAULT 0,
  status text DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Sent'::text, 'Paid'::text, 'Overdue'::text, 'Void'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT invoices_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.job_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  client_id uuid NOT NULL,
  service_id uuid,
  service_name text,
  frequency text CHECK (frequency = ANY (ARRAY['Weekly'::text, 'Biweekly'::text, 'Monthly'::text, 'Custom'::text])),
  preferred_day text,
  preferred_time time without time zone,
  pricing_type text DEFAULT 'Hourly'::text CHECK (pricing_type = ANY (ARRAY['Hourly'::text, 'Flat'::text])),
  hourly_rate numeric,
  estimated_hours numeric,
  flat_rate numeric,
  notes text,
  end_type text DEFAULT 'ongoing'::text CHECK (end_type = ANY (ARRAY['date'::text, 'count'::text, 'ongoing'::text])),
  end_date date,
  occurrences integer,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT job_templates_pkey PRIMARY KEY (id),
  CONSTRAINT job_templates_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT job_templates_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT job_templates_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  client_id uuid NOT NULL,
  service_id uuid,
  created_by uuid,
  template_id uuid,
  service_name text,
  scheduled_date date,
  scheduled_time time without time zone,
  scheduling_type text DEFAULT 'Hard Date'::text CHECK (scheduling_type = ANY (ARRAY['Hard Date'::text, 'ASAP'::text, 'By Date'::text])),
  completion_date date,
  original_scheduled_date date,
  reschedule_count integer DEFAULT 0,
  reschedule_reason text,
  pricing_type text DEFAULT 'Hourly'::text CHECK (pricing_type = ANY (ARRAY['Hourly'::text, 'Flat'::text])),
  hourly_rate numeric,
  estimated_hours numeric,
  actual_duration numeric,
  flat_rate numeric,
  surcharge numeric DEFAULT 0,
  tax_enabled boolean DEFAULT NULL, -- NULL = inherit from business.tax_enabled; true/false = per-job override
  hst_rate numeric DEFAULT 0.13,
  subtotal numeric DEFAULT 0,
  hst_amount numeric DEFAULT 0,
  additional_cost numeric DEFAULT 0,
  additional_cost_notes text,
  discount_amount numeric DEFAULT 0,
  discount_reason text,
  total_amount numeric DEFAULT 0,
  job_status text DEFAULT 'Scheduled'::text CHECK (job_status = ANY (ARRAY['Scheduled'::text, 'Completed'::text, 'Cancelled'::text])),
  payment_status text DEFAULT ''::text CHECK (payment_status = ANY (ARRAY[''::text, 'Partial'::text, 'Paid'::text])),
  payment_method text,
  prepaid_amount numeric DEFAULT 0,
  prepaid_reason text,
  job_notes text,
  completion_notes text,
  follow_up boolean DEFAULT false,
  follow_up_notes text,
  review_status text DEFAULT ''::text CHECK (review_status = ANY (ARRAY[''::text, 'Pending'::text, 'Requested'::text, 'Received'::text])),
  review_notes text,
  satisfaction_score smallint CHECK (satisfaction_score >= 1 AND satisfaction_score <= 5),
  cancellation_reason text,
  cancellation_date date,
  photo_links text,
  calendar_event_id text,
  ai_context jsonb DEFAULT '{}'::jsonb,
  distance_to_km numeric(7,2),
  distance_home_km numeric(7,2),
  invoice_sent_at timestamp with time zone,
  receipt_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT jobs_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT jobs_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT jobs_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.job_templates(id)
);
CREATE TABLE public.notification_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  client_id uuid NOT NULL,
  job_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['Job Reminder'::text, 'Invoice Due'::text, 'Follow Up'::text, 'Booking Confirmation'::text, 'Payment Received'::text, 'Review Request'::text, 'Custom'::text])),
  channel text CHECK (channel = ANY (ARRAY['SMS'::text, 'Email'::text, 'Push'::text, 'Manual'::text])),
  message text,
  scheduled_for timestamp with time zone,
  sent_at timestamp with time zone,
  status text DEFAULT 'Pending'::text CHECK (status = ANY (ARRAY['Pending'::text, 'Sent'::text, 'Failed'::text, 'Cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_log_pkey PRIMARY KEY (id),
  CONSTRAINT notification_log_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT notification_log_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT notification_log_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  invoice_id uuid,
  job_id uuid,
  client_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method text,
  payment_date date DEFAULT CURRENT_DATE,
  notes text,
  is_void boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  service_name text NOT NULL,
  refresh_token text NOT NULL,
  calendar_id text DEFAULT 'primary'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integrations_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE,
  CONSTRAINT integrations_business_id_service_name_key UNIQUE (business_id, service_name)
);

CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  pricing_type text DEFAULT 'Hourly'::text CHECK (pricing_type = ANY (ARRAY['Hourly'::text, 'Flat'::text])),
  default_price numeric DEFAULT 0,
  default_duration numeric DEFAULT 120,
  description text,
  active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.template_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  template_id uuid NOT NULL,
  job_id uuid,
  scheduled_date date NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'generated'::text, 'skipped'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT template_schedule_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT template_schedule_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.job_templates(id),
  CONSTRAINT template_schedule_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  business_id uuid,
  first_name text,
  last_name text,
  email text,
  role text NOT NULL DEFAULT 'worker'::text CHECK (role = ANY (ARRAY['admin'::text, 'owner'::text, 'worker'::text])),
  hourly_rate numeric,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.skill_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT skill_types_pkey PRIMARY KEY (id),
  CONSTRAINT skill_types_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT skill_types_business_name_key UNIQUE (business_id, name)
);
CREATE TABLE public.worker_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  worker_id uuid NOT NULL,
  skill_type_id uuid NOT NULL,
  pay_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT worker_skills_pkey PRIMARY KEY (id),
  CONSTRAINT worker_skills_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT worker_skills_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT worker_skills_skill_type_id_fkey FOREIGN KEY (skill_type_id) REFERENCES public.skill_types(id),
  CONSTRAINT worker_skills_worker_skill_unique UNIQUE (worker_id, skill_type_id)
);
-- workers.person_type added in v0.10.0: 'worker' (no app access) | 'staff' (future app access)
-- ALTER TABLE workers ADD COLUMN person_type text NOT NULL DEFAULT 'worker' CHECK (person_type IN ('worker','staff'));